### ISSUE TITLE
Add cases/tests breakdown by age-group / gender

### ISSUE THREAD

**Issue by adlerpriit** [neuroactive/koroonakaart#11]
Not sure the data is available, but would be good to see how the tests / cases distribute across different age groups and / or gender.

**Comment by neuroactive** [comment]
This is also something we have planned if we can obtain the necessary data.

**Comment by neuroactive** [comment]
As the code for this app is now being maintained by Open Data Estonia, I have moved this issue to their repository:

https://github.com/okestonia/koroonakaart/issues/9
