### ISSUE TITLE
Add number of severe, hospitalised cases

### ISSUE THREAD

**Issue by adlerpriit** [neuroactive/koroonakaart#12]
That would be nice indication of the current pressure on health case system. Could also be breakdown on how many currently hospitalised cases versus cumulative.

**Comment by neuroactive** [comment]
Thanks for the suggestion. We do plan to add this if we can get hold of the relevant data.

**Comment by neuroactive** [comment]
As the code for this app is now being maintained by Open Data Estonia, I have moved this issue to their repository:

https://github.com/okestonia/koroonakaart/issues/8
