### ISSUE TITLE
Relative heatmap

### ISSUE THREAD

**Issue by aomaesalu** [neuroactive/koroonakaart#4]
Currently, the heatmap seems to be based on absolute values. However, as over 40% of the population lives in Harju county, that is going to define the map. Having a heatmap with values relative to the population of the corresponding counties could improve the overview of the spread of the virus. You could have a toggle to switch whether to use absolute or relative values, so the page would not get too convoluted with different charts.

**Comment by neuroactive** [comment]
Thanks for the feedback. That's a reasonable point, and we are looking to improve the options for how the graph is presented. We are somewhat limited by time and resources at present.

**Comment by zidik** [comment]
Using the Number of cases relative to number of inhabitants would really make sense for the heatmap; It would give a better sense of prevalence of the virus in the region.

But could this be skewed by the availability of the testing in each region? Would number of cases relative to people tested would make more sense?

- x positive

**Comment by aomaesalu** [comment]
Yes, I agree with @zidik. However, is there information on the number of tests by county?

**Comment by neuroactive** [comment]
We are planning to make it possible to present the map using cases by number of inhabitants.

Unfortunately, county-level information about tests hasn't been made available to us yet.

**Comment by aomaesalu** [comment]
It turns out that the statistics is based on the locations of the laboratories that analysed the tests, not the places of residence of the infected. Only 6 counties have a testing laboratory: Harju, Tartu, Pärnu, Saare, Võru and Ida-Viru ([source](https://www.err.ee/1064312/koroonastatistika-ei-naita-mitte-nakatunute-elukohta-vaid-labori-asukohta)). Therefore, a heatmap with values relative to the population would be impossible, as there is no way to know whether a test for someone residing in, for example, the Valga county, was analysed in the Tartu or Võru testing site. The Estonian Health Board has stated that they do not have the capability of providing statistics based on residence.

Related issue: #8

**Comment by neuroactive** [comment]
As the code for this app is now being maintained by Open Data Estonia, I have moved this issue to their repository:

https://github.com/okestonia/koroonakaart/issues/14
