### ISSUE TITLE
Rotate numbers on bar chart

### ISSUE THREAD

**Issue by aomaesalu** [neuroactive/koroonakaart#5]
The numbers on the right-hand-side bar chart displaying the number of confirmed cases by county are rotated 90 degrees clockwise. This hurts legibility and there does not seem to be a good reason for it. Additionally, should the country get to a point where a single county has 100+ cases, the numbers wouldn't fit anymore without increasing the width of the bars. Could the numbers be rotated, so they would be the right way up?

**Comment by neuroactive** [comment]
That's strange, I seem those number orientated the correct way. Which browser are you using?

**Comment by aomaesalu** [comment]
`

Google Chrome | 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Linux
JavaScript | V8 8.0.426.19
Flash | 32.0.0.344 /home/aom/.config/google-chrome/PepperFlash/32.0.0.344/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36

`

**Comment by aomaesalu** [comment]
Here's a screenshot: https://imgur.com/a/wYu17E1

**Comment by neuroactive** [comment]
Thanks.

We are using an external library, Plotly, for the charts, so our capacity to fix this may be limited. I have done some tests and the numbers are displaying vertically in Chrome and Edge on Windows. In Firefox, half the numbers are vertically-oriented and half sideways :)

**Comment by neuroactive** [comment]
As the code for this app is now being maintained by Open Data Estonia, I have moved this issue to their repository:

https://github.com/okestonia/koroonakaart/issues/13
