### ISSUE TITLE
Compare number of tests to confirmed cases

### ISSUE THREAD

**Issue by aomaesalu** [neuroactive/koroonakaart#6]
Currently, the number of tests and the number of confirmed cases are displayed on separate charts. That is great for clarity. However, from March 12 onwards, these numbers already seem to be heavily correlated. This indicates that the number of tests could be a bottleneck. Therefore, it would be interesting to have some way to compare these two values over time.

**Comment by neuroactive** [comment]
Right, we displayed those on separate charts in the interest of clarity. We will bear in mind your suggestion to make it possible to compare those values.

We are exploring what other data we could present in relation to the tests. We feel it would be useful, for example, to add data about how many tests are being done by region. However, whether this is possible depends entirely on whether the relevant authorities will be prepared to release such data to us.

**Comment by neuroactive** [comment]
As the code for this app is now being maintained by Open Data Estonia, I have moved this issue to their repository:

https://github.com/okestonia/koroonakaart/issues/12
