### ISSUE TITLE
Separate Ida-Viru and Lääne-Viru counties

### ISSUE THREAD

**Issue by aomaesalu** [neuroactive/koroonakaart#7]
Ida-Viru and Lääne-Viru counties are two separate counties. They are both visible on the map, but on the bar chart, there is only one, and with the wrong name (Virumaa). This might be confusing.

**Comment by neuroactive** [comment]
We are sourcing our data from the public press releases made by Terviseamet at the moment, and the information it published was that 8 cases had been diagnosed in "Virumaa". We do plan to list Ida-Viru and Lääne-Viru separately as soon as we have suitable data.

**Comment by aomaesalu** [comment]
Lääne-Viru county does not have a testing laboratory. Only 6 counties have one: Harju, Tartu, Pärnu, Saare, Võru and Ida-Viru ([source](https://www.err.ee/1064312/koroonastatistika-ei-naita-mitte-nakatunute-elukohta-vaid-labori-asukohta)). Therefore, "Virumaa" should represent Ida-Viru county in this context.

**Comment by aomaesalu** [comment]
Related issue: #8

**Comment by aomaesalu** [comment]
Resolved.
