### ISSUE TITLE
Statistics are based on testing laboratories, not residence

### ISSUE THREAD

**Issue by aomaesalu** [neuroactive/koroonakaart#8]
The number of cases stated by the Estonian Health Board does not reflect the location of residence of the infected, but rather the location of the testing laboratories. Only 6 counties have testing sites and the Estonian Health Board does not have the capability of providing statistics based on residence ([source](https://www.err.ee/1064312/koroonastatistika-ei-naita-mitte-nakatunute-elukohta-vaid-labori-asukohta)). Consequently, you may want to remove counties with no cases from the bar chart, as the infected might still reside in these counties.

Using a heatmap might be misleading, as well, because it seems to (incorrectly) indicate that there are no cases of infected people in Hiiu, Järva, Jõgeva, Lääne, Lääne-Viru, Põlva, Rapla, Valga and Viljandi counties. Instead of a heatmap-type color scale, you could use points with varying size (based on the number of confirmed cases) at the locations of the laboratories. These points could also be pie charts, denoting the proportion of active, recovered and deceased cases.

**Comment by keeganmcbride** [comment]
Thanks for pointing this out, we have heard this from a few other sources as well and have hidden this information as we wait for data from terviseamet.

**Comment by aomaesalu** [comment]
Resolved.
